/**
 * ListIcon Component
 * Renders a Lucide icon based on the icon name from ListIconName type
 */

import {
  Folder,
  FolderOpen,
  Briefcase,
  Home,
  Heart,
  Star,
  Bookmark,
  Flag,
  Target,
  Lightbulb,
  Rocket,
  Gift,
  ShoppingCart,
  Music,
  Camera,
  BookOpen,
  GraduationCap,
  Archive,
  Zap,
  Trophy,
  CreditCard,
  Calendar,
  Clock,
  AlarmClock,
  Sun,
  Moon,
  Users,
  User,
  Building,
  Stethoscope,
  Plane,
  Car,
  Bike,
  MapPin,
  Globe,
  Ban,
  Film,
  Tv,
  Gamepad2,
  MessageCircle,
  Code,
  Terminal,
  Database,
  Server,
  Cpu,
  Smartphone,
  Mail,
  Phone,
  MessageSquare,
  Send,
  Rss,
  Clipboard,
  FileText,
  // Finance & Money
  Wallet,
  DollarSign,
  CircleDollarSign,
  PiggyBank,
  Receipt,
  Percent,
  Calculator,
  TrendingUp,
  BarChart3,
  // Security & Privacy
  Lock,
  Unlock,
  Key,
  Shield,
  ShieldCheck,
  Eye,
  // Tools & Creative
  Settings,
  Wrench,
  Hammer,
  Paintbrush,
  Palette,
  Pen,
  Scissors,
  // Food & Drink
  Coffee,
  Wine,
  UtensilsCrossed,
  Pizza,
  Apple,
  // Nature & Weather
  Leaf,
  TreePine,
  Flower2,
  Flame,
  Snowflake,
  Mountain,
  Waves,
  Cloud,
  Umbrella,
  // Fitness & Health
  Dumbbell,
  Activity,
  HeartPulse,
  Pill,
  Brain,
  // Science & Education
  Atom,
  FlaskConical,
  Microscope,
  // Social & Events
  Crown,
  Diamond,
  Sparkles,
  PartyPopper,
  Cake,
  Baby,
  // Audio & Media
  Headphones,
  Podcast,
  Megaphone,
  Bell,
  // Organization
  Tag,
  Hash,
  Paperclip,
  Layers,
  Kanban,
  ListTodo,
  Anchor,
  Compass,
  LucideIcon,
} from 'lucide-react';
import { ListIconName } from '@/types';
import { cn } from '@/lib/utils';

const iconMap: Record<ListIconName, LucideIcon> = {
  'folder': Folder,
  'folder-open': FolderOpen,
  'briefcase': Briefcase,
  'home': Home,
  'heart': Heart,
  'star': Star,
  'bookmark': Bookmark,
  'flag': Flag,
  'target': Target,
  'lightbulb': Lightbulb,
  'rocket': Rocket,
  'gift': Gift,
  'shopping-cart': ShoppingCart,
  'music': Music,
  'camera': Camera,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  'archive': Archive,
  'zap': Zap,
  'trophy': Trophy,
  'credit-card': CreditCard,
  'calendar': Calendar,
  'clock': Clock,
  'alarm-clock': AlarmClock,
  'sun': Sun,
  'moon': Moon,
  'users': Users,
  'user': User,
  'building': Building,
  'stethoscope': Stethoscope,
  'plane': Plane,
  'car': Car,
  'bike': Bike,
  'map-pin': MapPin,
  'globe': Globe,
  'ban': Ban,
  'film': Film,
  'tv': Tv,
  'gamepad': Gamepad2,
  'message-circle': MessageCircle,
  'code': Code,
  'terminal': Terminal,
  'database': Database,
  'server': Server,
  'cpu': Cpu,
  'smartphone': Smartphone,
  'mail': Mail,
  'phone': Phone,
  'message-square': MessageSquare,
  'send': Send,
  'rss': Rss,
  'clipboard': Clipboard,
  'file-text': FileText,
  // Finance & Money
  'wallet': Wallet,
  'dollar-sign': DollarSign,
  'circle-dollar-sign': CircleDollarSign,
  'piggy-bank': PiggyBank,
  'receipt': Receipt,
  'percent': Percent,
  'calculator': Calculator,
  'trending-up': TrendingUp,
  'bar-chart-3': BarChart3,
  // Security & Privacy
  'lock': Lock,
  'unlock': Unlock,
  'key': Key,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'eye': Eye,
  // Tools & Creative
  'settings': Settings,
  'wrench': Wrench,
  'hammer': Hammer,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'pen': Pen,
  'scissors': Scissors,
  // Food & Drink
  'coffee': Coffee,
  'wine': Wine,
  'utensils-crossed': UtensilsCrossed,
  'pizza': Pizza,
  'apple': Apple,
  // Nature & Weather
  'leaf': Leaf,
  'tree-pine': TreePine,
  'flower': Flower2,
  'flame': Flame,
  'snowflake': Snowflake,
  'mountain': Mountain,
  'waves': Waves,
  'cloud': Cloud,
  'umbrella': Umbrella,
  // Fitness & Health
  'dumbbell': Dumbbell,
  'activity': Activity,
  'heart-pulse': HeartPulse,
  'pill': Pill,
  'brain': Brain,
  // Science & Education
  'atom': Atom,
  'flask-conical': FlaskConical,
  'microscope': Microscope,
  // Social & Events
  'crown': Crown,
  'diamond': Diamond,
  'sparkles': Sparkles,
  'party-popper': PartyPopper,
  'cake': Cake,
  'baby': Baby,
  // Audio & Media
  'headphones': Headphones,
  'podcast': Podcast,
  'megaphone': Megaphone,
  'bell': Bell,
  // Organization
  'tag': Tag,
  'hash': Hash,
  'paperclip': Paperclip,
  'layers': Layers,
  'kanban': Kanban,
  'list-todo': ListTodo,
  'anchor': Anchor,
  'compass': Compass,
};

interface ListIconProps {
  name: ListIconName;
  className?: string;
  color?: string;
}

export function ListIcon({ name, className, color }: ListIconProps) {
  const Icon = iconMap[name] || Folder;
  
  return (
    <Icon 
      className={cn('w-4 h-4', className)} 
      style={color ? { color } : undefined}
    />
  );
}
